
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sirenix.OdinInspector;

namespace ET
{ 
    public enum ENumericDefinitionType
    {
        /// <summary>
        /// 无
        /// </summary>
	    [LabelText("无")]
        None = -1,
        /// <summary>
        /// 结果
        /// </summary>
	    [LabelText("结果")]
        Result = 0,
        /// <summary>
        /// 基础
        /// </summary>
	    [LabelText("基础")]
        Base = 1,
        /// <summary>
        /// 基础增加
        /// </summary>
	    [LabelText("基础增加")]
        Add = 2,
        /// <summary>
        /// 基础百分比
        /// </summary>
	    [LabelText("基础百分比")]
        Pct = 3,
        /// <summary>
        /// 最终增加
        /// </summary>
	    [LabelText("最终增加")]
        FinalAdd = 4,
        /// <summary>
        /// 最终百分比
        /// </summary>
	    [LabelText("最终百分比")]
        FinalPct = 5,
        /// <summary>
        /// 结果增加
        /// </summary>
	    [LabelText("结果增加")]
        ResultAdd = 6,
    }
} 

