
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sirenix.OdinInspector;

namespace ET
{ 
    public enum ENumericType
    {
        /// <summary>
        /// 无
        /// </summary>
	    [LabelText("无")]
        None = 0,
        /// <summary>
        /// 测试_0 (Int)
        /// </summary>
	    [LabelText("测试_0 (Int)")]
        NumericTest0 = 100000,
        /// <summary>
        /// 临时1数据_0 (Int)
        /// </summary>
	    [LabelText("临时1数据_0 (Int)")]
        Temp1Data0 = 990001,
        /// <summary>
        /// 临时2数据_0 (Int)
        /// </summary>
	    [LabelText("临时2数据_0 (Int)")]
        Temp2Data0 = 990002,
        /// <summary>
        /// 临时3数据_0 (Int)
        /// </summary>
	    [LabelText("临时3数据_0 (Int)")]
        Temp3Data0 = 990003,
        /// <summary>
        /// 临时4数据_0 (Int)
        /// </summary>
	    [LabelText("临时4数据_0 (Int)")]
        Temp4Data0 = 990004,
        /// <summary>
        /// 临时5数据_0 (Int)
        /// </summary>
	    [LabelText("临时5数据_0 (Int)")]
        Temp5Data0 = 990005,
        /// <summary>
        /// 临时6数据_0 (Int)
        /// </summary>
	    [LabelText("临时6数据_0 (Int)")]
        Temp6Data0 = 990006,
        /// <summary>
        /// 临时7数据_0 (Int)
        /// </summary>
	    [LabelText("临时7数据_0 (Int)")]
        Temp7Data0 = 990007,
        /// <summary>
        /// 临时8数据_0 (Int)
        /// </summary>
	    [LabelText("临时8数据_0 (Int)")]
        Temp8Data0 = 990008,
        /// <summary>
        /// 临时9数据_0 (Int)
        /// </summary>
	    [LabelText("临时9数据_0 (Int)")]
        Temp9Data0 = 990009,
        /// <summary>
        /// 临时10数据_0 (Int)
        /// </summary>
	    [LabelText("临时10数据_0 (Int)")]
        Temp10Data0 = 990010,
        /// <summary>
        /// 等级_0 (Int)
        /// </summary>
	    [LabelText("等级_0 (Int)")]
        Level0 = 100001,
        /// <summary>
        /// 经验值_0 (Int)
        /// </summary>
	    [LabelText("经验值_0 (Int)")]
        Exp0 = 100002,
        /// <summary>
        /// 金钱_0 (Int)
        /// </summary>
	    [LabelText("金钱_0 (Int)")]
        Money0 = 100003,
        /// <summary>
        /// 钻石_0 (Int)
        /// </summary>
	    [LabelText("钻石_0 (Int)")]
        Diamond0 = 100004,
        /// <summary>
        /// 当前血量_0 (Int)
        /// </summary>
	    [LabelText("当前血量_0 (Int)")]
        Hp0 = 200001,
        /// <summary>
        /// 最大血量_0 (Int)
        /// </summary>
	    [LabelText("最大血量_0 (Int)")]
        MaxHp0 = 200002,
        /// <summary>
        /// 最大血量_1 (Int)
        /// </summary>
	    [LabelText("最大血量_1 (Int)")]
        MaxHp1 = 2000021,
        /// <summary>
        /// 最大血量_2 (Int)
        /// </summary>
	    [LabelText("最大血量_2 (Int)")]
        MaxHp2 = 2000022,
        /// <summary>
        /// 最大血量_3 (Float)
        /// </summary>
	    [LabelText("最大血量_3 (Float)")]
        MaxHp3 = 2000023,
        /// <summary>
        /// 最大血量_4 (Int)
        /// </summary>
	    [LabelText("最大血量_4 (Int)")]
        MaxHp4 = 2000024,
        /// <summary>
        /// 最大血量_5 (Float)
        /// </summary>
	    [LabelText("最大血量_5 (Float)")]
        MaxHp5 = 2000025,
        /// <summary>
        /// 最大血量_6 (Int)
        /// </summary>
	    [LabelText("最大血量_6 (Int)")]
        MaxHp6 = 2000026,
        /// <summary>
        /// 速度_0 (Float)
        /// </summary>
	    [LabelText("速度_0 (Float)")]
        Speed0 = 200003,
        /// <summary>
        /// 速度_1 (Float)
        /// </summary>
	    [LabelText("速度_1 (Float)")]
        Speed1 = 2000031,
        /// <summary>
        /// 速度_2 (Float)
        /// </summary>
	    [LabelText("速度_2 (Float)")]
        Speed2 = 2000032,
        /// <summary>
        /// 速度_3 (Float)
        /// </summary>
	    [LabelText("速度_3 (Float)")]
        Speed3 = 2000033,
        /// <summary>
        /// 速度_4 (Float)
        /// </summary>
	    [LabelText("速度_4 (Float)")]
        Speed4 = 2000034,
        /// <summary>
        /// 速度_5 (Float)
        /// </summary>
	    [LabelText("速度_5 (Float)")]
        Speed5 = 2000035,
        /// <summary>
        /// 速度_6 (Float)
        /// </summary>
	    [LabelText("速度_6 (Float)")]
        Speed6 = 2000036,
        /// <summary>
        /// AOI_0 (Float)
        /// </summary>
	    [LabelText("AOI_0 (Float)")]
        AOI0 = 200004,
        /// <summary>
        /// AOI_1 (Float)
        /// </summary>
	    [LabelText("AOI_1 (Float)")]
        AOI1 = 2000041,
        /// <summary>
        /// AOI_2 (Float)
        /// </summary>
	    [LabelText("AOI_2 (Float)")]
        AOI2 = 2000042,
        /// <summary>
        /// AOI_3 (Float)
        /// </summary>
	    [LabelText("AOI_3 (Float)")]
        AOI3 = 2000043,
        /// <summary>
        /// AOI_4 (Float)
        /// </summary>
	    [LabelText("AOI_4 (Float)")]
        AOI4 = 2000044,
        /// <summary>
        /// AOI_5 (Float)
        /// </summary>
	    [LabelText("AOI_5 (Float)")]
        AOI5 = 2000045,
        /// <summary>
        /// AOI_6 (Float)
        /// </summary>
	    [LabelText("AOI_6 (Float)")]
        AOI6 = 2000046,
    }
} 

