
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sirenix.OdinInspector;

namespace ET
{ 
    public enum ENumericValueType
    {
        /// <summary>
        /// EV_None
        /// </summary>
	    [LabelText("EV_None")]
        None = 0,
        /// <summary>
        /// EV_Init
        /// </summary>
	    [LabelText("EV_Init")]
        Int = 1,
        /// <summary>
        /// EV_Long
        /// </summary>
	    [LabelText("EV_Long")]
        Long = 2,
        /// <summary>
        /// EV_Bool
        /// </summary>
	    [LabelText("EV_Bool")]
        Bool = 3,
        /// <summary>
        /// EV_Float
        /// </summary>
	    [LabelText("EV_Float")]
        Float = 4,
    }
} 

