
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sirenix.OdinInspector;

namespace ET
{ 
    public enum ENumericNoticeType
    {
        /// <summary>
        /// 无
        /// </summary>
	    [LabelText("无")]
        None = 0,
        /// <summary>
        /// 自己
        /// </summary>
	    [LabelText("自己")]
        Self = 1,
        /// <summary>
        /// 全体
        /// </summary>
	    [LabelText("全体")]
        Broadcast = 2,
        /// <summary>
        /// 除自己外
        /// </summary>
	    [LabelText("除自己外")]
        BroadcastWithoutSelf = 3,
    }
} 

