
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class NumericFormulaConfigCategory : Singleton<NumericFormulaConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, NumericFormulaConfig> _dataMap;
        private readonly List<NumericFormulaConfig> _dataList;
        
        public NumericFormulaConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, NumericFormulaConfig>();
            _dataList = new List<NumericFormulaConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                NumericFormulaConfig _v;
                _v = global::ET.NumericFormulaConfig.DeserializeNumericFormulaConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, NumericFormulaConfig> GetAll() => _dataMap;
        public Dictionary<int, NumericFormulaConfig> DataMap => _dataMap;
        public List<NumericFormulaConfig> DataList => _dataList;

        public NumericFormulaConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public NumericFormulaConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

