
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericValueLimitNone : NumericValueLimitData
    {
        public NumericValueLimitNone(ByteBuf _buf)  : base(_buf) 
        {

            EndInit();
        }

        public static NumericValueLimitNone DeserializeNumericValueLimitNone(ByteBuf _buf)
        {
            return new NumericValueLimitNone(_buf);
        }

    
        public const int __ID__ = -822144145;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void EndRef();
    }

}

