
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericFormulaConfig : Luban.BeanBase
    {
        public NumericFormulaConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();

            EndInit();
        }

        public static NumericFormulaConfig DeserializeNumericFormulaConfig(ByteBuf _buf)
        {
            return new NumericFormulaConfig(_buf);
        }

        /// <summary>
        /// 这是id
        /// </summary>
        public readonly int Id;
    
        public const int __ID__ = -1222245797;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "}";
        }

        partial void EndRef();
    }

}

