
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sirenix.OdinInspector;

namespace ET
{ 
    [System.Flags]
    public enum ENumericTag
    {
        /// <summary>
        /// 无
        /// </summary>
	    [LabelText("无")]
        None = 0,
        /// <summary>
        /// 标签1
        /// </summary>
	    [LabelText("标签1")]
        Tag1 = 1,
        /// <summary>
        /// 标签2
        /// </summary>
	    [LabelText("标签2")]
        Tag2 = 2,
        /// <summary>
        /// 标签3
        /// </summary>
	    [LabelText("标签3")]
        Tag3 = 4,
        /// <summary>
        /// 标签4
        /// </summary>
	    [LabelText("标签4")]
        Tag4 = 8,
        /// <summary>
        /// 标签5
        /// </summary>
	    [LabelText("标签5")]
        Tag5 = 16,
        /// <summary>
        /// 标签6
        /// </summary>
	    [LabelText("标签6")]
        Tag6 = 32,
        /// <summary>
        /// 标签7
        /// </summary>
	    [LabelText("标签7")]
        Tag7 = 64,
        /// <summary>
        /// 标签8
        /// </summary>
	    [LabelText("标签8")]
        Tag8 = 128,
        /// <summary>
        /// 标签9
        /// </summary>
	    [LabelText("标签9")]
        Tag9 = 256,
        /// <summary>
        /// 标签10
        /// </summary>
	    [LabelText("标签10")]
        Tag10 = 512,
        /// <summary>
        /// 标签11
        /// </summary>
	    [LabelText("标签11")]
        Tag11 = 1024,
        /// <summary>
        /// 标签12
        /// </summary>
	    [LabelText("标签12")]
        Tag12 = 2048,
        /// <summary>
        /// 标签13
        /// </summary>
	    [LabelText("标签13")]
        Tag13 = 4096,
        /// <summary>
        /// 标签14
        /// </summary>
	    [LabelText("标签14")]
        Tag14 = 8192,
        /// <summary>
        /// 标签15
        /// </summary>
	    [LabelText("标签15")]
        Tag15 = 16384,
        /// <summary>
        /// 标签16
        /// </summary>
	    [LabelText("标签16")]
        Tag16 = 32768,
        /// <summary>
        /// 标签17
        /// </summary>
	    [LabelText("标签17")]
        Tag17 = 65536,
        /// <summary>
        /// 标签18
        /// </summary>
	    [LabelText("标签18")]
        Tag18 = 131072,
        /// <summary>
        /// 标签19
        /// </summary>
	    [LabelText("标签19")]
        Tag19 = 262144,
        /// <summary>
        /// 标签20
        /// </summary>
	    [LabelText("标签20")]
        Tag20 = 524288,
        /// <summary>
        /// 标签21
        /// </summary>
	    [LabelText("标签21")]
        Tag21 = 1048576,
        /// <summary>
        /// 标签22
        /// </summary>
	    [LabelText("标签22")]
        Tag22 = 2097152,
        /// <summary>
        /// 标签23
        /// </summary>
	    [LabelText("标签23")]
        Tag23 = 4194304,
        /// <summary>
        /// 标签24
        /// </summary>
	    [LabelText("标签24")]
        Tag24 = 8388608,
        /// <summary>
        /// 标签25
        /// </summary>
	    [LabelText("标签25")]
        Tag25 = 16777216,
        /// <summary>
        /// 标签26
        /// </summary>
	    [LabelText("标签26")]
        Tag26 = 33554432,
        /// <summary>
        /// 标签27
        /// </summary>
	    [LabelText("标签27")]
        Tag27 = 67108864,
        /// <summary>
        /// 标签28
        /// </summary>
	    [LabelText("标签28")]
        Tag28 = 134217728,
        /// <summary>
        /// 标签29
        /// </summary>
	    [LabelText("标签29")]
        Tag29 = 268435456,
        /// <summary>
        /// 标签30
        /// </summary>
	    [LabelText("标签30")]
        Tag30 = 536870912,
        /// <summary>
        /// 标签31
        /// </summary>
	    [LabelText("标签31")]
        Tag31 = 1073741824,
    }
} 

