
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sirenix.OdinInspector;

namespace ET
{ 
    public enum ENumericValueLimitType
    {
        /// <summary>
        /// 数字
        /// </summary>
	    [LabelText("数字")]
        Number = 0,
        /// <summary>
        /// 数值
        /// </summary>
	    [LabelText("数值")]
        Numeric = 1,
    }
} 

