
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericValueLimitFormula : NumericValueLimitData
    {
        public NumericValueLimitFormula(ByteBuf _buf)  : base(_buf) 
        {
            Value = _buf.ReadInt();
            Value_Ref = null;

            EndInit();
        }

        public static NumericValueLimitFormula DeserializeNumericValueLimitFormula(ByteBuf _buf)
        {
            return new NumericValueLimitFormula(_buf);
        }

        /// <summary>
        /// 值
        /// </summary>
        public readonly int Value;
        public NumericFormulaConfig Value_Ref;
    
        public const int __ID__ = -1098748465;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef()
        {
            base.ResolveRef();
            Value_Ref = NumericFormulaConfigCategory.Instance.GetOrDefault(Value);
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "value:" + Value + ","
            + "}";
        }

        partial void EndRef();
    }

}

