
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    /// <summary>
    /// 全局参数配置(key-value)
    /// </summary>
    [Config]
    public partial class GlobalParamConfigCategory : Singleton<GlobalParamConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<string, GlobalParamConfig> _dataMap;
        private readonly List<GlobalParamConfig> _dataList;
        
        public GlobalParamConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<string, GlobalParamConfig>();
            _dataList = new List<GlobalParamConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                GlobalParamConfig _v;
                _v = global::ET.GlobalParamConfig.DeserializeGlobalParamConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<string, GlobalParamConfig> GetAll() => _dataMap;
        public Dictionary<string, GlobalParamConfig> DataMap => _dataMap;
        public List<GlobalParamConfig> DataList => _dataList;

        public GlobalParamConfig GetOrDefault(string key) => _dataMap.GetValueOrDefault(key);

        public GlobalParamConfig Get(string key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

