
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class GlobalParamConfig : Luban.BeanBase
    {
        public GlobalParamConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadString();
            Value = _buf.ReadFloat();

            EndInit();
        }

        public static GlobalParamConfig DeserializeGlobalParamConfig(ByteBuf _buf)
        {
            return new GlobalParamConfig(_buf);
        }

        /// <summary>
        /// 参数名
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// 参数值
        /// </summary>
        public readonly float Value;
    
        public const int __ID__ = 218790508;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Value:" + Value + ","
            + "}";
        }

        partial void EndRef();
    }

}

