
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericValueLimitNumericAdd : NumericValueLimitData
    {
        public NumericValueLimitNumericAdd(ByteBuf _buf)  : base(_buf) 
        {
            {int n0 = _buf.ReadSize(); Value = new System.Collections.Generic.List<ENumericType>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ENumericType _e0;  _e0 = (ENumericType)_buf.ReadInt(); Value.Add(_e0);}}

            EndInit();
        }

        public static NumericValueLimitNumericAdd DeserializeNumericValueLimitNumericAdd(ByteBuf _buf)
        {
            return new NumericValueLimitNumericAdd(_buf);
        }

        /// <summary>
        /// 值
        /// </summary>
        public readonly System.Collections.Generic.List<ENumericType> Value;
    
        public const int __ID__ = 875564363;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "value:" + Luban.StringUtil.CollectionToString(Value) + ","
            + "}";
        }

        partial void EndRef();
    }

}

